### ISSUE TITLE
When i do npm start

### ISSUE THREAD

**Issue by tomyprs** [sgratzl/developer_webhook_bot#9]
> developer_webhook_bot@1.0.0 start /home/kai-net/developer_webhook_bot
> node -r dotenv/config ./build/bot

```
/home/kai-net/developer_webhook_bot/node_modules/telegraf/lib/core/helpers/compact.js:11
    return Object.fromEntries(compactEntries);
                  ^

TypeError: Object.fromEntries is not a function
    at Object.compactOptions (/home/kai-net/developer_webhook_bot/node_modules/telegraf/lib/core/helpers/compact.js:11:19)
    at new ApiClient (/home/kai-net/developer_webhook_bot/node_modules/telegraf/lib/core/network/client.js:208:26)
    at new Telegram (/home/kai-net/developer_webhook_bot/node_modules/telegraf/lib/telegram.js:7:1)
    at new Telegraf (/home/kai-net/developer_webhook_bot/node_modules/telegraf/lib/telegraf.js:45:25)
    at Object.<anonymous> (/home/kai-net/developer_webhook_bot/build/bot.js:37:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! developer_webhook_bot@1.0.0 start: `node -r dotenv/config ./build/bot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the developer_webhook_bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kai-net/.npm/_logs/2021-07-08T04_58_16_535Z-debug.log
```

**Comment by sgratzl** [comment]
seems like you are using an old version of node.js which doesn't support Object.entries yet

**Comment by tomyprs** [comment]
> seems like you are using an old version of node.js which doesn't support Object.entries yet

nodejs 10

**Comment by tomyprs** [comment]
now get 

``(node:61853) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:330:9)
    at Object.createSecret (/home/kai-net/developer_webhook_bot/build/_internal/secret.js:7:62)
    at Object.webhookMessage (/home/kai-net/developer_webhook_bot/build/webhooks/gitlab/[chatid].js:172:29)
    at /home/kai-net/developer_webhook_bot/build/bot.js:60:29
    at /home/kai-net/developer_webhook_bot/node_modules/telegraf/lib/composer.js:324:28    at /home/kai-net/developer_webhook_bot/node_modules/telegraf/lib/composer.js:158:111
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async execute (/home/kai-net/developer_webhook_bot/node_modules/telegraf/lib/composer.js:458:17)
    at async /home/kai-net/developer_webhook_bot/node_modules/telegraf/lib/composer.js:459:21
    at async execute (/home/kai-net/developer_webhook_bot/node_modules/telegraf/lib/composer.js:458:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:61853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:61853) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
``

After /webhook command and choose github

**Comment by sgratzl** [comment]
you need two environment variables:
 1. BOT_TOKEN for the bot token
 2. WEBHOOK_SECRET for creating webhook secrets.
I assume the latter one is missing

**Comment by tomyprs** [comment]
ah webhook secret, why is this not in simple config?

**Comment by sgratzl** [comment]
which config? I created this bot mainly for myself so there isn't much documentation about it

**Comment by tomyprs** [comment]
ah thank btw for support , now bot working

**Comment by tomyprs** [comment]
Bro where we can deploy this?
Please use this webhook url:
  /webhooks/github/1856655168
    Content-Type: application/json
    Secret: bcb7c0e9feceaea37a98488d0fdaadaf625c1850
But this doesnt work

**Comment by sgratzl** [comment]
I deployed this whole project on https://vercel.com/ and it keeps running there

**Comment by tomyprs** [comment]
Well, why here after deploy complete, nothing actions. Bot also not working sed

**Comment by tomyprs** [comment]
After deployed in local isn't working. This repo just can deploy in vercel?
